version: "3.1"

services:
  mysql:
    build: .
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: labcal
      MYSQL_USER: labcal
      MYSQL_PASSWORD: labcal
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
